import logging
from typing import List

from core.base_llm import BaseLLM
from core.base_retriever import BaseRetriever
from core.base_reranker import BaseReranker
from core.schemas import ParsedQuery, Chunk
from pipeline.query_processor import QueryProcessor

# Configure basic logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class RAGPipeline:
    """
    The central orchestrator that strings together the entire RAG lifecycle:
    Query Parsing -> Hybrid Retrieval -> Cross-encoder Reranking -> LLM Generation.
    Uses Dependency Injection to remain completely agnostic to the underlying models.
    """

    def __init__(
        self,
        parser_llm: BaseLLM,
        retriever: BaseRetriever,
        reranker: BaseReranker,
        generator_llm: BaseLLM,
    ):
        """
        Initializes the pipeline with specific implementations of the core interfaces.

        Args:
            parser_llm: A fast, lightweight LLM (e.g., 0.5B) dedicated to parsing.
            retriever: The retrieval engine (e.g., PostgreSQL Hybrid Search).
            reranker: The cross-encoder model for deep semantic re-scoring.
            generator_llm: The main LLM for drafting the final answer.
        """
        self.processor = QueryProcessor(llm=parser_llm)
        self.retriever = retriever
        self.reranker = reranker
        self.generator_llm = generator_llm

    def run(self, raw_query: str) -> str:
        """
        Executes the end-to-end RAG workflow.

        Args:
            raw_query (str): The initial question inputted by the user.

        Returns:
            str: The final, context-aware answer generated by the LLM.
        """
        print("\n" + "=" * 60)
        print("INITIATING RAG PIPELINE")
        print(f"👉 USER QUERY: '{raw_query}'")
        print("=" * 60)

        # ---------------------------------------------------------
        # Step 1: Query Parsing & Validation
        # ---------------------------------------------------------
        print("\n[Step 1/4] Parsing Query & Extracting Filters...")
        parsed_data: ParsedQuery = self.processor.process(raw_query)

        # ---------------------------------------------------------
        # Step 2: Hybrid Retrieval (Semantic + FTS inside DB)
        # ---------------------------------------------------------
        print("\n[Step 2/4] Retrieving from Database")
        # Fetch a broader set of candidates (e.g., top 20) to give the reranker enough options
        initial_chunks: List[Chunk] = self.retriever.retrieve(
            query=parsed_data.optimized_query, top_k=20, filters=parsed_data.filters
        )

        if not initial_chunks:
            logger.warning("No relevant documents found in the database.")
            return "I'm sorry, but I couldn't find any relevant functions in the documentation to answer your question."

        # ---------------------------------------------------------
        # Step 3: Cross-encoder Reranking
        # ---------------------------------------------------------
        print(f"\n[Step 3/4] Reranking {len(initial_chunks)} candidates...")
        # Rerank and keep only the absolute best for the LLM context
        best_chunks: List[Chunk] = self.reranker.rerank(
            query=parsed_data.optimized_query, chunks=initial_chunks, top_k=5
        )

        # ---------------------------------------------------------
        # Step 4: Prompt Building & LLM Generation
        # ---------------------------------------------------------
        print("\n[Step 4/4] Generating Final Answer...")
        final_answer = self.generator_llm.generate_answer(
            query=raw_query, context_chunks=best_chunks
        )

        print("\n" + "=" * 60)
        print("✅ PIPELINE COMPLETE")
        print("=" * 60 + "\n")

        return final_answer
